// Registro de novedades (Ajustes → Novedades), la más nueva arriba. Agregar una entrada con cada versión que valga la pena contar.
export const NOVEDADES = [
  { v: "2.46.2", items: ["Filtrar y ordenar: sin el botón «Todos» (sin nada marcado se ven todos).", "La fecha que se muestra en la lista ahora se elige en Ajustes, debajo de Apariencia."] },
  { v: "2.46.1", items: ["Notificaciones: también aparece lo que se carga de desmontaje."] },
  { v: "2.46.0", items: ["Filtrar y ordenar en un solo botón, con opciones más claras (pintura, repuestos, grado, turnos, compañías).", "Notificaciones: la campanita avisa los cambios que hacen otros en los vehículos.", "Celular: Ajustes ahora está en el menú de operativos, junto con Gestionar, Unirme y Crear."] },
  { v: "2.45.44", items: ["Al actualizar: un auto acelera y cruza la pantalla, con ruido de motor."] },
  { v: "2.45.43", items: ["Computadora: los estados del inicio en una fila a lo ancho, arriba de la búsqueda."] },
  { v: "2.45.41", items: ["PDF: la firma va en su propia hoja, antes de las fotos."] },
  { v: "2.45.40", items: ["Planilla del perito sin total.", "Eliminar un operativo ahora pide confirmación por WhatsApp al creador."] },
  { v: "2.45.39", items: ["Link de peritos: también ven la planilla, solo con sus vehículos."] },
  { v: "2.45.38", items: ["Panel del creador: elegir quién ve Técnicos, Gastos y Gastos fijos."] },
  { v: "2.45.37", items: ["Cierre: a los de sueldo se puede elegir «Descontar gastos»; si no, los gastos quedan aparte."] },
  { v: "2.45.36", items: ["Planilla de técnicos: al tocar un técnico la tabla queda donde la deslizaste."] },
  { v: "2.45.35", items: ["Sueldos: desde/hasta, monto y opción fijo mensual; agregar técnicos que solo están a sueldo."] },
  { v: "2.45.33", items: ["Planilla de técnicos: pestañas Sacabollos, Sueldos y Cierre (con todos).", "Viandas y alquiler de PABLO y RODRI se suman al sacabollo PAB+ROD."] },
  { v: "2.45.32", items: ["Cierre: abajo aparecen los técnicos que solo están en viandas o alquiler, para cerrarlos ahí."] },
  { v: "2.45.31", items: ["Alquiler: la fecha de inicio solo se cambia al editar."] },
  { v: "2.45.30", items: ["Viandas: «Cambiar técnicos o valores» aparece solo al editar.", "Links de perito cortos con vista previa en WhatsApp."] },
  { v: "2.45.28", items: ["Alquiler: «Reparto total» plegable, columna «Corresponde», técnicos solo al editar y copiar/pegar fechas entre técnicos."] },
  { v: "2.45.27", items: ["Alquiler: se cuentan noches (el día de salida no se cobra)."] },
  { v: "2.45.26", items: ["Alquiler: varias casas, cada una con su nombre, sus pagos y sus estadías."] },
  { v: "2.45.25", items: ["Planilla de gastos: los gastos fijos se suman al total y aparecen en el mismo resumen."] },
  { v: "2.45.24", items: ["Alquiler: cada pago con fecha de inicio y de fin.", "Alquiler: varias estadías por técnico (llegó / se fue)."] },
  { v: "2.45.23", items: ["Planilla de gastos: los gastos fijos (viandas y alquiler) aparecen arriba, aparte de los comunes.", "Gastos fijos: técnicos en orden de ingreso."] },
  { v: "2.45.20", items: ["Viandas: los domingos no se cuentan.", "Viandas más simple: listado por día y total por técnico plegable."] },
  { v: "2.45.17", items: ["Viandas: listado por día con quiénes estuvieron y cuánto gastó cada uno."] },
  { v: "2.45.16", items: ["Modo oscuro más oscuro (gris/negro en vez de azul)."] },
  { v: "2.45.15", items: ["Agregar personas: buscador con los usuarios de la app (sin escribir el @usuario).", "Rol por defecto al agregar: Administrador."] },
  { v: "2.45.14", items: ["Gastos fijos con su propia lista de técnicos.", "Gestión del operativo: @usuario debajo de cada nombre."] },
  { v: "2.45.10", items: ["Aviso de versión nueva: un autito arriba a la derecha; al tocarlo se actualiza.", "Novedades en Ajustes.", "iPhone instalada: barra superior sólida debajo de la isla.", "Operativos ordenados por fecha de creación."] },
  { v: "2.45.5", items: ["Pantalla de inicio de sesión clara, con botón para modo oscuro."] },
  { v: "2.45.3", items: ["Ícono de la web y vistas previas al compartir links.", "Links de perito y de vehículo con formato nuevo."] },
  { v: "2.45.2", items: ["Mantener apretado el paso de reparación o Facturado para cambiar fechas.", "Facturado con un solo toque (fecha de hoy)."] },
  { v: "2.45.0", items: ["Gastos fijos: viandas y alquiler repartidos entre los técnicos.", "Planilla de técnicos sin compañía y con «marcado por defecto»."] },
  { v: "2.44.9", items: ["Compartir → «Vehículo en App»: link para ver solo ese vehículo."] }
];
